name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1
    - uses: actions/setup-python@v2.2.2
    - run: python Build.py
    - name: Upload Moonlight
      if: github.ref != 'refs/heads/master'
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Moonlight
        path: "${{ github.workspace }}/SpotLight/bin/x64/Moonlight_RELEASE"
    - name: Upload Spotlight
      if: github.ref != 'refs/heads/master'
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Spotlight
        path: "${{ github.workspace }}/SpotLight/bin/x86/Spotlight_RELEASE"
    - name: Make a release
      if: github.ref == 'refs/heads/master'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Auto"
        prerelease: true
        title: "Auto Build"
        files: |
          *.zip
